# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-10-05 05:20
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('insta', '0002_remove_posts_profile'),
    ]

    operations = [
        migrations.AddField(
            model_name='posts',
            name='profile',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='insta.Profile'),
        ),
    ]
