# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-10-05 08:30
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('insta', '0003_posts_profile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='posts',
            name='image',
            field=models.ImageField(upload_to='posts'),
        ),
    ]
