# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-10-04 14:27
from __future__ import unicode_literals

from django.db import migrations
import tinymce.models


class Migration(migrations.Migration):

    dependencies = [
        ('insta', '0003_profile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='bio',
            field=tinymce.models.HTMLField(max_length=500),
        ),
    ]
