# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-10-07 12:09
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('insta', '0008_likes'),
    ]

    operations = [
        migrations.AddField(
            model_name='likes',
            name='like',
            field=models.CharField(default='1', max_length=3),
        ),
    ]
