# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-10-07 12:25
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('insta', '0010_auto_20181007_1224'),
    ]

    operations = [
        migrations.AlterField(
            model_name='likes',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='l_user', to=settings.AUTH_USER_MODEL),
        ),
    ]
