# -*- coding: utf-8 -*-
# Generated by Django 1.11.17 on 2019-07-25 11:29
from __future__ import unicode_literals

from django.db import migrations
import pyuploadcare.dj.models


class Migration(migrations.Migration):

    dependencies = [
        ('insta', '0012_profile_email_confirmed'),
    ]

    operations = [
        migrations.AlterField(
            model_name='posts',
            name='image',
            field=pyuploadcare.dj.models.ImageField(blank=True),
        ),
        migrations.AlterField(
            model_name='profile',
            name='dp',
            field=pyuploadcare.dj.models.ImageField(blank=True),
        ),
    ]
